spring:
  application:
    name: achun-gateway
  data:
    redis:
      host: 192.168.100.104
      port: 6379
      database: 0
      password: yunbin
      ssl:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka.apiv5.achun.site/eureka/
server:
  port: 9500
logging:
  file:
    name: /data/logs/achun/file/info.log
